# Generated by Django 4.2.7 on 2025-12-23 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swipe_type', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass'), ('super_like', 'Super Like')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_user', 'to_user'], name='matching_sw_from_us_b4449f_idx'), models.Index(fields=['to_user', 'swipe_type'], name='matching_sw_to_user_974c82_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('user1_seen', models.BooleanField(default=False)),
                ('user2_seen', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-matched_at'],
                'indexes': [models.Index(fields=['user1', 'user2'], name='matching_ma_user1_i_284bbf_idx'), models.Index(fields=['is_active', 'matched_at'], name='matching_ma_is_acti_26f49b_idx')],
            },
        ),
    ]
